###

POST https://capston1-fqm6.onrender.com/userdb
content-type: application/json

{
    "username":"Henry",
    "ppr": 0,
    "dpr": 0
}



#########

PUT http://localhost:8081/userdb
content-type: application/json

{"username":"eugene","ppr":4.0,"dpr":8.0}
###

GET http://localhost:8081/userdb


###

GET http://localhost:8081/StatsBoard/users/eugene
Accept: text/html

###

GET https://capston1-fqm6.onrender.com/StatsBoard/users
Accept: text/html
 
###

GET https://capston1-fqm6.onrender.com/StatsBoard/users/Henry
Accept: text/html

###

GET http://localhost:8081/StatsBoard/users
Accept: text/html



###

GET http://localhost:8081/
Accept: text/html

###

POST http://localhost:8081/login
content-type: application/json

{
    "username":"tret",
    "password": "1234"
}